# see https://docs.travis-ci.com/user/languages/java

language: java

# The build require a postgres instance, see https://docs.travis-ci.com/user/database-setup/
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database sigmah;' -U postgres
